<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_rc_car">

  <!-- Define properties for easy modification -->
  <xacro:property name="chassis_length" value="0.4"/>
  <xacro:property name="chassis_width" value="0.2"/>
  <xacro:property name="chassis_height" value="0.1"/>
  <xacro:property name="chassis_mass" value="5.0"/>
  
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  
  <xacro:property name="wheelbase" value="0.3"/>
  <xacro:property name="track_width" value="0.25"/>

  <!-- Define colors -->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Base link (required for ROS 2) -->
  <link name="base_link"/>

  <!-- Chassis link -->
  <link name="chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia 
        ixx="${(1/12) * chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height)}"
        iyz="0.0"
        izz="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <!-- Joint connecting base_link to chassis -->
  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Wheel macro for easy duplication -->
  <xacro:macro name="wheel" params="prefix suffix reflect_lr reflect_fb">
    <link name="${prefix}_${suffix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia 
          ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
          ixy="0.0" ixz="0.0"
          iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
          iyz="0.0"
          izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <origin xyz="${reflect_fb * wheelbase/2} ${reflect_lr * track_width/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>
  </xacro:macro>

  <!-- Create all four wheels -->
  <xacro:wheel prefix="front" suffix="left" reflect_lr="1" reflect_fb="1"/>
  <xacro:wheel prefix="front" suffix="right" reflect_lr="-1" reflect_fb="1"/>
  <xacro:wheel prefix="rear" suffix="left" reflect_lr="1" reflect_fb="-1"/>
  <xacro:wheel prefix="rear" suffix="right" reflect_lr="-1" reflect_fb="-1"/>

  <!-- Lidar Link -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.125"/>
      <inertia 
        ixx="0.000020833" ixy="0.0" ixz="0.0"
        iyy="0.000020833" iyz="0.0"
        izz="0.000028125"/>
    </inertial>
  </link>

  <!-- Lidar Joint (fixed to top of chassis) -->
  <joint name="lidar_joint" type="fixed">
    <parent link="chassis"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${chassis_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo-specific configurations -->
  <gazebo reference="chassis">
    <material>Gazebo/Blue</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="front_left_wheel">
    <material>Gazebo/Black</material>
    <mu1>100.0</mu1>
    <mu2>50.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <minDepth>0.005</minDepth>
    <maxVel>1.0</maxVel>
    <fdir1>1 0 0</fdir1>
  </gazebo>

  <gazebo reference="front_right_wheel">
    <material>Gazebo/Black</material>
    <mu1>100.0</mu1>
    <mu2>50.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <minDepth>0.005</minDepth>
    <maxVel>1.0</maxVel>
    <fdir1>1 0 0</fdir1>
  </gazebo>

  <gazebo reference="rear_left_wheel">
    <material>Gazebo/Black</material>
    <mu1>100.0</mu1>
    <mu2>50.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <minDepth>0.005</minDepth>
    <maxVel>1.0</maxVel>
    <fdir1>1 0 0</fdir1>
  </gazebo>

  <gazebo reference="rear_right_wheel">
    <material>Gazebo/Black</material>
    <mu1>100.0</mu1>
    <mu2>50.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <minDepth>0.005</minDepth>
    <maxVel>1.0</maxVel>
    <fdir1>1 0 0</fdir1>
  </gazebo>

  <!-- Lidar Sensor Gazebo Plugin -->
  <gazebo reference="lidar_link">
    <sensor name="lidar_sensor" type="ray">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <!-- Update rate in Hz -->
      <update_rate>50</update_rate>

      <!-- Wheels -->
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>

      <!-- Kinematics -->
      <wheel_separation>${track_width}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>

      <!-- Limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- Output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>

      <!-- Topics -->
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
    </plugin>
  </gazebo>

  <!-- Joint State Publisher Plugin -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>50</update_rate>
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>rear_left_wheel_joint</joint_name>
      <joint_name>rear_right_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>